export type RealisticEquipmentAsset = {
  id: string;
  label: string;
  sublabel: string;
  svgPath: string;
  legacySvgPath?: string;
};

export const realisticEquipmentAssets: RealisticEquipmentAsset[] = [
  {
    id: "beaker-250ml",
    label: "Beaker",
    sublabel: "250 mL",
    svgPath: "/assets/equipment-realistic/v1/beaker-250ml.svg",
    legacySvgPath: "/assets/equipment/beaker-250ml.svg",
  },
  {
    id: "analytical-balance",
    label: "Balance",
    sublabel: "0.01 g",
    svgPath: "/assets/equipment-realistic/v1/analytical-balance.svg",
    legacySvgPath: "/assets/equipment/analytical-balance.svg",
  },
  {
    id: "graduated-cylinder-100ml",
    label: "Graduated Cylinder",
    sublabel: "100 mL",
    svgPath: "/assets/equipment-realistic/v1/graduated-cylinder-100ml.svg",
    legacySvgPath: "/assets/equipment/graduated-cylinder.svg",
  },
  {
    id: "funnel-filter-paper",
    label: "Funnel + Filter Paper",
    sublabel: "11 cm",
    svgPath: "/assets/equipment-realistic/v1/funnel-filter-paper.svg",
    legacySvgPath: "/assets/equipment/funnel-stand.svg",
  },
  {
    id: "watch-glass",
    label: "Watch Glass",
    sublabel: "75 mm",
    svgPath: "/assets/equipment-realistic/v1/watch-glass.svg",
    legacySvgPath: "/assets/equipment/watch-glass.svg",
  },
  {
    id: "volumetric-flask",
    label: "Volumetric Flask",
    sublabel: "100 mL",
    svgPath: "/assets/equipment-realistic/v1/volumetric-flask.svg",
    legacySvgPath: "/assets/equipment/volumetric-flask.svg",
  },
  {
    id: "wash-bottle",
    label: "Wash Bottle",
    sublabel: "500 mL",
    svgPath: "/assets/equipment-realistic/v1/wash-bottle.svg",
    legacySvgPath: "/assets/equipment/wash-bottle.svg",
  },
  {
    id: "reagent-bottle",
    label: "Reagent Bottle",
    sublabel: "250 mL",
    svgPath: "/assets/equipment-realistic/v1/reagent-bottle.svg",
    legacySvgPath: "/assets/equipment/reagent-bottle.svg",
  },
  {
    id: "sample-rack",
    label: "Sample Rack",
    sublabel: "Tubes",
    svgPath: "/assets/equipment-realistic/v1/sample-rack.svg",
    legacySvgPath: "/assets/equipment/sample-rack.svg",
  },
  {
    id: "filter-paper",
    label: "Filter Paper",
    sublabel: "11 cm",
    svgPath: "/assets/equipment-realistic/v1/filter-paper.svg",
    legacySvgPath: "/assets/equipment/filter-paper.svg",
  },
  {
    id: "chromatography-paper",
    label: "Chromatography Paper",
    sublabel: "Cellulose",
    svgPath: "/assets/equipment-realistic/v1/chromatography-paper.svg",
    legacySvgPath: "/assets/equipment/chromatography-paper.svg",
  },
  {
    id: "chromatography-chamber",
    label: "Chromatography Chamber",
    sublabel: "Solvent jar",
    svgPath: "/assets/equipment-realistic/v1/chromatography-chamber.svg",
    legacySvgPath: "/assets/equipment/chromatography-chamber.svg",
  },
  {
    id: "capillary-spotter",
    label: "Capillary Spotter",
    sublabel: "Glass",
    svgPath: "/assets/equipment-realistic/v1/capillary-spotter.svg",
    legacySvgPath: "/assets/equipment/capillary-spotter.svg",
  },
  {
    id: "metric-ruler",
    label: "Metric Ruler",
    sublabel: "10 cm",
    svgPath: "/assets/equipment-realistic/v1/metric-ruler.svg",
    legacySvgPath: "/assets/equipment/metric-ruler.svg",
  },
  {
    id: "pencil",
    label: "Pencil",
    sublabel: "Graphite",
    svgPath: "/assets/equipment-realistic/v1/pencil.svg",
  },
  {
    id: "stirring-rod",
    label: "Stirring Rod",
    sublabel: "Glass",
    svgPath: "/assets/equipment-realistic/v1/stirring-rod.svg",
    legacySvgPath: "/assets/equipment/stirring-rod.svg",
  },
  {
    id: "spatula",
    label: "Spatula",
    sublabel: "Steel",
    svgPath: "/assets/equipment-realistic/v1/spatula.svg",
    legacySvgPath: "/assets/equipment/spatula.svg",
  },
  {
    id: "crucible-tongs",
    label: "Crucible Tongs",
    sublabel: "Steel",
    svgPath: "/assets/equipment-realistic/v1/crucible-tongs.svg",
    legacySvgPath: "/assets/equipment/crucible-tongs.svg",
  },
  {
    id: "drying-oven",
    label: "Drying Oven",
    sublabel: "Benchtop",
    svgPath: "/assets/equipment-realistic/v1/drying-oven.svg",
    legacySvgPath: "/assets/equipment/drying-oven.svg",
  },
  {
    id: "erlenmeyer-flask-250ml",
    label: "Erlenmeyer Flask",
    sublabel: "250 mL",
    svgPath: "/assets/equipment-realistic/v1/erlenmeyer-flask-250ml.svg",
  },
  {
    id: "burette-50ml",
    label: "Burette",
    sublabel: "50 mL",
    svgPath: "/assets/equipment-realistic/v1/burette-50ml.svg",
  },
  {
    id: "volumetric-pipette-10ml",
    label: "Volumetric Pipette",
    sublabel: "10 mL",
    svgPath: "/assets/equipment-realistic/v1/volumetric-pipette-10ml.svg",
  },
  {
    id: "pipette-bulb",
    label: "Pipette Bulb",
    sublabel: "Rubber",
    svgPath: "/assets/equipment-realistic/v1/pipette-bulb.svg",
  },
  {
    id: "test-tube",
    label: "Test Tube",
    sublabel: "18 x 150 mm",
    svgPath: "/assets/equipment-realistic/v1/test-tube.svg",
  },
  {
    id: "test-tube-holder",
    label: "Test Tube Holder",
    sublabel: "Wood",
    svgPath: "/assets/equipment-realistic/v1/test-tube-holder.svg",
  },
  {
    id: "hot-plate-stirrer",
    label: "Hot Plate Stirrer",
    sublabel: "Ceramic top",
    svgPath: "/assets/equipment-realistic/v1/hot-plate-stirrer.svg",
  },
  {
    id: "bunsen-burner",
    label: "Bunsen Burner",
    sublabel: "Gas",
    svgPath: "/assets/equipment-realistic/v1/bunsen-burner.svg",
  },
  {
    id: "spectrophotometer",
    label: "Spectrophotometer",
    sublabel: "630 nm",
    svgPath: "/assets/equipment-realistic/v1/spectrophotometer.svg",
  },
  {
    id: "cuvette",
    label: "Cuvette",
    sublabel: "4 mL",
    svgPath: "/assets/equipment-realistic/v1/cuvette.svg",
  },
  {
    id: "ring-stand-clamp",
    label: "Ring Stand + Clamp",
    sublabel: "Support",
    svgPath: "/assets/equipment-realistic/v1/ring-stand-clamp.svg",
  },
  {
    id: "evaporating-dish",
    label: "Evaporating Dish",
    sublabel: "Porcelain",
    svgPath: "/assets/equipment-realistic/v1/evaporating-dish.svg",
  },
  {
    id: "crucible-with-lid",
    label: "Crucible + Lid",
    sublabel: "Porcelain",
    svgPath: "/assets/equipment-realistic/v1/crucible-with-lid.svg",
  },
  {
    id: "mortar-pestle",
    label: "Mortar + Pestle",
    sublabel: "Porcelain",
    svgPath: "/assets/equipment-realistic/v1/mortar-pestle.svg",
  },
  {
    id: "separatory-funnel",
    label: "Separatory Funnel",
    sublabel: "250 mL",
    svgPath: "/assets/equipment-realistic/v1/separatory-funnel.svg",
  },
  {
    id: "round-bottom-flask-250ml",
    label: "Round-Bottom Flask",
    sublabel: "250 mL",
    svgPath: "/assets/equipment-realistic/v1/round-bottom-flask-250ml.svg",
  },
  {
    id: "condenser",
    label: "Liebig Condenser",
    sublabel: "Glass",
    svgPath: "/assets/equipment-realistic/v1/condenser.svg",
  },
  {
    id: "thermometer",
    label: "Thermometer",
    sublabel: "Lab",
    svgPath: "/assets/equipment-realistic/v1/thermometer.svg",
  },
  {
    id: "gas-syringe",
    label: "Gas Syringe",
    sublabel: "100 mL",
    svgPath: "/assets/equipment-realistic/v1/gas-syringe.svg",
  },
  {
    id: "rubber-stopper-delivery-tube",
    label: "Stopper + Tube",
    sublabel: "Gas delivery",
    svgPath: "/assets/equipment-realistic/v1/rubber-stopper-delivery-tube.svg",
  },
  {
    id: "marble-chips",
    label: "Marble Chips",
    sublabel: "CaCO3",
    svgPath: "/assets/equipment-realistic/v1/marble-chips.svg",
  },
  {
    id: "stopwatch",
    label: "Stopwatch",
    sublabel: "Digital",
    svgPath: "/assets/equipment-realistic/v1/stopwatch.svg",
  },
  {
    id: "ph-meter",
    label: "pH Meter",
    sublabel: "Digital",
    svgPath: "/assets/equipment-realistic/v1/ph-meter.svg",
  },
  {
    id: "dropper-bottle",
    label: "Dropper Bottle",
    sublabel: "Amber",
    svgPath: "/assets/equipment-realistic/v1/dropper-bottle.svg",
  },
  {
    id: "petri-dish",
    label: "Petri Dish",
    sublabel: "Glass",
    svgPath: "/assets/equipment-realistic/v1/petri-dish.svg",
  },
  {
    id: "glass-slide",
    label: "Microscope Slide",
    sublabel: "Glass",
    svgPath: "/assets/equipment-realistic/v1/glass-slide.svg",
  },
  {
    id: "forceps",
    label: "Forceps",
    sublabel: "Steel",
    svgPath: "/assets/equipment-realistic/v1/forceps.svg",
  },
  {
    id: "scoopula",
    label: "Scoopula",
    sublabel: "Steel",
    svgPath: "/assets/equipment-realistic/v1/scoopula.svg",
  },
  {
    id: "weigh-boat",
    label: "Weigh Boat",
    sublabel: "Plastic",
    svgPath: "/assets/equipment-realistic/v1/weigh-boat.svg",
  },
  {
    id: "clay-triangle",
    label: "Clay Triangle",
    sublabel: "Support",
    svgPath: "/assets/equipment-realistic/v1/clay-triangle.svg",
  },
  {
    id: "wire-gauze",
    label: "Wire Gauze",
    sublabel: "Ceramic center",
    svgPath: "/assets/equipment-realistic/v1/wire-gauze.svg",
  },
  {
    id: "rubber-stopper-set",
    label: "Rubber Stoppers",
    sublabel: "Set",
    svgPath: "/assets/equipment-realistic/v1/rubber-stopper-set.svg",
  },
  {
    id: "desiccator",
    label: "Desiccator",
    sublabel: "Glass",
    svgPath: "/assets/equipment-realistic/v1/desiccator.svg",
  },
  {
    id: "centrifuge-tube",
    label: "Centrifuge Tube",
    sublabel: "15 mL",
    svgPath: "/assets/equipment-realistic/v1/centrifuge-tube.svg",
  },
  {
    id: "foam-cup-calorimeter",
    label: "Foam Calorimeter Cup",
    sublabel: "8 oz polystyrene",
    svgPath: "/assets/equipment-realistic/v1/foam-cup-calorimeter.svg",
  },
  {
    id: "wooden-calorimeter-lid",
    label: "Calorimeter Lid",
    sublabel: "Wood cover",
    svgPath: "/assets/equipment-realistic/v1/wooden-calorimeter-lid.svg",
  },
  {
    id: "stir-bar",
    label: "PTFE Stir Bar",
    sublabel: "Magnetic",
    svgPath: "/assets/equipment-realistic/v1/stir-bar.svg",
  },
  {
    id: "magnetic-stirrer",
    label: "Magnetic Stirrer",
    sublabel: "Stirring base",
    svgPath: "/assets/equipment-realistic/v1/magnetic-stirrer.svg",
  },
  {
    id: "hot-plate",
    label: "Hot Plate",
    sublabel: "Bench heater",
    svgPath: "/assets/equipment-realistic/v1/hot-plate.svg",
  },
  {
    id: "dixie-cup",
    label: "Dixie Cup",
    sublabel: "Sample cup",
    svgPath: "/assets/equipment-realistic/v1/dixie-cup.svg",
  },
  {
    id: "lab-scoop",
    label: "Lab Scoop",
    sublabel: "Solid transfer",
    svgPath: "/assets/equipment-realistic/v1/lab-scoop.svg",
  },
];
