/**
 * The equipment3d registry contract (plan §4.3). Entries are keyed by catalogue definition id and
 * generated by tools/blender/pack_models.py from each model's meta.json; never edit
 * registry.json by hand.
 *
 * Coordinates are model-local millimetres: x to the viewer's right, y away from the default
 * viewer, z up, with the origin at the footprint centre on the bench plane. The viewer converts
 * them to three.js Y-up; runtime bench units are converted only in adapters/benchCoordinates.
 */
export type Vec3Mm = number[];

export type Equipment3DFootprint =
  | { shape: "circle"; radius: number }
  | { shape: "rect"; width: number; depth: number };

export interface Equipment3DPour {
  /** The point liquid leaves the source, model-local. */
  lipMm: Vec3Mm;
  /** Tilt used when the committed pour animates (handoff §5.7). */
  tiltDeg: number;
  /** "pour" tips from a lip; "squeeze-jet" is a wash bottle's delivery tube. */
  style?: "pour" | "squeeze-jet";
  tipDirection?: Vec3Mm;
}

export interface Equipment3DFill {
  /** Inner surface-of-revolution profile, [radius, height] pairs in mm, height increasing. */
  innerProfileMm?: number[][];
  /** Rectangular inner cavity (a cuvette), used instead of a profile. */
  innerBoxMm?: { width: number; depth: number; floorZ: number; topZ: number };
  /** Equals the catalogue capacity; the profile must hold at least this much. */
  capacityMl: number;
  meniscus: "concave" | "convex" | "flat";
}

export interface Equipment3DGraduations {
  unit: "mL";
  minor: number;
  major: number;
  maxMl: number;
}

/** Where a powder or other solid heap rests inside or on the item (plan §2.6: powder when solid). */
export interface Equipment3DSolidRest {
  centreMm: Vec3Mm;
  radiusMm: number;
}

/** A calibration ring (a volumetric flask): the height at which the item holds `ml`. */
export interface Equipment3DCalibration {
  ml: number;
  heightMm: number;
}

/** A zone anchor, keyed by semantic zone id from src/domain/interactionZones.ts. */
export interface Equipment3DAnchor {
  positionMm: Vec3Mm;
  /** Rotation of the seated child about z, in degrees. */
  yawDeg?: number;
}

/** A display surface; `policy` names an entry in displayPolicies.json (measurement-neutral). */
export interface Equipment3DDisplay {
  id: string;
  policy: string;
  /** Centre of the display face, model-local. */
  centreMm: Vec3Mm;
  sizeMm: number[];
}

export interface Equipment3DProvenance {
  blender: string;
  generator: string;
  sourceHash: string;
}

export interface Equipment3DEntry {
  definitionId: string;
  model: string;
  thumbnail: string;
  footprintMm: Equipment3DFootprint;
  grip: { heightMm: number };
  pour?: Equipment3DPour;
  fill?: Equipment3DFill;
  graduations: Equipment3DGraduations | null;
  calibration?: Equipment3DCalibration;
  /** The scenery id that holds this item upright when it stands on the bench (decision D9). */
  requiresSupport?: string;
  solidRest?: Equipment3DSolidRest;
  anchors: Record<string, Equipment3DAnchor>;
  displays: Equipment3DDisplay[];
  /** Named visual states (for example a stopper seated or removed); presentation only. */
  states: Record<string, unknown>;
  /** Visual-only bench scenery (decision D9): never an equipment instance, never selectable. */
  scenery?: boolean;
  /** For scenery: the catalogue definition it supports, and where that item's origin sits. */
  sceneryFor?: { definitionId: string; seatsMm: Vec3Mm[] };
  provenance: Equipment3DProvenance;
}

export interface Equipment3DRegistry {
  schema: string;
  generatedBy: string;
  coordinates: string;
  assetBase: string;
  entries: Equipment3DEntry[];
}
