import type {
  CapabilityEntry,
  CapabilityManifestFragment,
  CapabilityProof,
  CapabilityProofRef,
  CapabilityRef,
} from "../../platform/capabilities/types";

const version = "1.0.0";
const platePathId = "assay.accessible.plate-grid-table";
const pipettingPathId = "assay.accessible.pipetting-workbench";
const dilutionPathId = "assay.accessible.dilution-formula-table";
const assignmentPathId = "assay.accessible.control-replicate-editor";
const qcPathId = "assay.accessible.qc-chart-table";
const planningPathId = "assay.accessible.operational-plan";
const ingestionPathId = "assay.accessible.observation-import-review";
const protocolAnalysisPathId = "assay.accessible.protocol-analysis";
const releaseReviewPathId = "assay.accessible.release-review";
const operationEvidenceId = "assay.pipetting-operation";
const assignmentEvidenceId = "assay.assignment-change";
const observationEvidenceId = "assay.observation";
const qcEvidenceId = "assay.qc-result";
const normalizedEvidenceId = "assay.normalized-result";
const formulaTraceEvidenceId = "assay.formula-trace";
const runPlanEvidenceId = "run.plan";
const ingestedObservationEvidenceId = "assay.ingested-observation";
const ref = (kind: CapabilityRef["kind"], id: string): CapabilityRef => ({
  domainPackId: "assay",
  kind,
  id,
  version,
});
const proofRef = (proofId: string, kind: CapabilityProofRef["kind"]): CapabilityProofRef => ({ proofId, kind });

const proofs: CapabilityProof[] = [
  {
    id: "assay.release.shared-services-v1",
    kind: "validator",
    title: "Shared direct-app and MCP assay release services",
    implementation: { source: "src/domain-packs/assay/services/releaseServices.ts", exportName: "assayReleaseServices" },
    dependsOnProofRefs: [], evidenceTypeIds: [], accessiblePathIds: [releaseReviewPathId],
    limitations: ["The services are stateless and bounded to registered 96-well artifacts, profiles, schemas, and explicit caller inputs."],
  },
  {
    id: "assay.release.review-ui-v1",
    kind: "interaction-implementation",
    title: "Validation, semantic compare/apply, and release export review",
    implementation: { source: "src/assay/release/AssayReleaseReview.tsx", exportName: "AssayReleaseReview" },
    dependsOnProofRefs: ["assay.release.shared-services-v1"], evidenceTypeIds: [], accessiblePathIds: [releaseReviewPathId],
    limitations: ["Apply is blocked for invalid or mismatched artifacts; downloads contain reviewable text/JSON/CSV only."],
  },
  {
    id: "assay.release.accessible-review-v1",
    kind: "accessible-path",
    title: "Keyboard and screen-reader assay release review",
    implementation: { source: "src/assay/release/AssayReleaseReview.tsx", exportName: "AssayReleaseReview" },
    dependsOnProofRefs: ["assay.release.review-ui-v1"], evidenceTypeIds: [], accessiblePathIds: [releaseReviewPathId],
    limitations: ["Validation, changes, boundaries, and files are exposed as text, tables, disclosures, and native buttons."],
  },
  {
    id: "assay.release.tests-v1",
    kind: "regression-test",
    title: "Assay release services and six-tool MCP contract source",
    implementation: { source: "src/domain-packs/assay/services/__tests__/releaseServices.test.ts" },
    dependsOnProofRefs: ["assay.release.shared-services-v1"], evidenceTypeIds: [], accessiblePathIds: [releaseReviewPathId],
    limitations: ["Detailed test execution is intentionally deferred under repository policy; this source is not claimed as an executed result."],
  },
  {
    id: "assay.fixture.layout-v1",
    kind: "representative-content-fixture",
    title: "96-well layout conformance fixture",
    implementation: { source: "src/domain-packs/assay/__fixtures__/assay-layout.v1.ts", exportName: "assayLayoutGoldenArtifact" },
    dependsOnProofRefs: [], evidenceTypeIds: [], accessiblePathIds: [],
    limitations: ["The fixture proves authored representation only; it performs no liquid transfer or analysis."],
  },
  {
    id: "assay.validation.artifact-v1",
    kind: "validator",
    title: "AssayDefinition and plate-invariant validator",
    implementation: { source: "src/domain-packs/assay/types/validation.ts", exportName: "validateAssayDefinition" },
    dependsOnProofRefs: ["assay.fixture.layout-v1"], evidenceTypeIds: [], accessiblePathIds: [],
    limitations: ["Artifact validation covers schema, references, coordinates, volumes, and capacity; runtime operations use a separate validator."],
  },
  {
    id: "assay.view.plate-editor-v1",
    kind: "interaction-implementation",
    title: "Semantic 96-well grid and table representation",
    implementation: { source: "src/assay/AssayPlateEditor.tsx", exportName: "AssayPlateEditor" },
    dependsOnProofRefs: ["assay.fixture.layout-v1"], evidenceTypeIds: [], accessiblePathIds: [platePathId],
    limitations: ["This view authors and inspects a plate map; it is not a signal heatmap."],
  },
  {
    id: "assay.accessible.plate-grid-table-v1",
    kind: "accessible-path",
    title: "Keyboard and screen-reader plate table parity",
    implementation: { source: "src/assay/AssayPlateEditor.tsx", exportName: "AssayPlateTable" },
    dependsOnProofRefs: ["assay.view.plate-editor-v1"], evidenceTypeIds: [], accessiblePathIds: [platePathId],
    limitations: ["Accessible parity covers the plate-map representation and selection behavior."],
  },
  {
    id: "assay.runtime.pipetting-v1",
    kind: "runtime-handler",
    title: "Immutable assay pipetting reducer",
    implementation: { source: "src/domain-packs/assay/runtime/reducer.ts", exportName: "reduceAssayRuntime" },
    dependsOnProofRefs: [], evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId],
    limitations: [
      "The reducer models nominal deterministic volume and composition only.",
      "Robotic hardware, stochastic error, quantitative carryover, air gaps, and reverse pipetting are not modeled.",
    ],
  },
  {
    id: "assay.validation.pipetting-operation-v1",
    kind: "validator",
    title: "Assay pipetting operation validator",
    implementation: { source: "src/domain-packs/assay/runtime/validation.ts", exportName: "validateAssayOperation" },
    dependsOnProofRefs: ["assay.runtime.pipetting-v1"], evidenceTypeIds: [], accessiblePathIds: [],
    limitations: ["Capacity, mixing, tip compatibility, and source-volume prerequisites are enforced atomically by the reducer."],
  },
  {
    id: "assay.interaction.pipetting-workbench-v1",
    kind: "interaction-implementation",
    title: "Assay pipetting rehearsal controls",
    implementation: { source: "src/assay/player/AssayPipettingRehearsal.tsx", exportName: "AssayPipettingRehearsal" },
    dependsOnProofRefs: ["assay.runtime.pipetting-v1"], evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId],
    limitations: ["The workbench exposes nominal single-channel and eight-channel rehearsal; it does not control laboratory hardware."],
  },
  {
    id: "assay.evidence.pipetting-operation-v1",
    kind: "evidence-producer",
    title: "Allowlisted assay operation evidence projection",
    implementation: { source: "src/domain-packs/assay/runtime/evidence.ts", exportName: "projectAssayOperationEvidence" },
    dependsOnProofRefs: ["assay.runtime.pipetting-v1"], evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId],
    limitations: ["Pipetting evidence records attempted transitions; Cycle 08 adds separate reviewed observation, QC, normalization, and trace evidence."],
  },
  {
    id: "assay.accessible.pipetting-workbench-v1",
    kind: "accessible-path",
    title: "Native keyboard, pointer, and screen-reader pipetting controls",
    implementation: { source: "src/assay/player/AssayPipettingRehearsal.tsx", exportName: "AssayPipettingWorkbench" },
    dependsOnProofRefs: ["assay.interaction.pipetting-workbench-v1"], evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId],
    limitations: ["Pointer and keyboard activation share the same intent dispatcher; direct numeric and plate selections use native form controls."],
  },
  {
    id: "assay.tests.pipetting-runtime-v1",
    kind: "regression-test",
    title: "Pipetting runtime, mapping, and conservation regressions",
    implementation: { source: "src/domain-packs/assay/runtime/__tests__/runtime.test.ts" },
    dependsOnProofRefs: ["assay.runtime.pipetting-v1", "assay.interaction.pipetting-workbench-v1"],
    evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId],
    limitations: ["Regression coverage is not device calibration or physical accuracy evidence."],
  },
  {
    id: "assay.tests.pipetting-workbench-v1",
    kind: "regression-test",
    title: "Pipetting pointer, keyboard, feedback, and semantic-trace regressions",
    implementation: { source: "src/assay/player/__tests__/AssayPipettingWorkbench.test.tsx" },
    dependsOnProofRefs: ["assay.interaction.pipetting-workbench-v1", "assay.accessible.pipetting-workbench-v1"],
    evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId],
    limitations: ["Component regression coverage does not establish physical equipment accuracy or calibration."],
  },
  {
    id: "assay.fixture.complete-96-well-dilution-plan-v1",
    kind: "representative-content-fixture",
    title: "Complete 96-well exact serial-dilution plan fixture",
    implementation: { source: "src/domain-packs/assay/dilution/__fixtures__/complete96WellPlan.ts", exportName: "getComplete96WellSerialDilutionPlan" },
    dependsOnProofRefs: [], evidenceTypeIds: [], accessiblePathIds: [dilutionPathId],
    limitations: ["The fixture uses explicit nominal inputs and is not a protocol-specific QC or calibration profile."],
  },
  {
    id: "assay.interaction.dilution-formula-summary-v1",
    kind: "interaction-implementation",
    title: "Exact dilution formula and conservation summary",
    implementation: { source: "src/assay/player/AssayDilutionPlanSummary.tsx", exportName: "AssayDilutionPlanSummary" },
    dependsOnProofRefs: ["assay.fixture.complete-96-well-dilution-plan-v1"], evidenceTypeIds: [], accessiblePathIds: [dilutionPathId],
    limitations: ["The summary displays generated nominal formula traces and conservation totals; it is not a plate-reader or QC result view."],
  },
  {
    id: "assay.accessible.dilution-formula-summary-v1",
    kind: "accessible-path",
    title: "Semantic dilution formula-trace table",
    implementation: { source: "src/assay/player/AssayDilutionPlanSummary.tsx", exportName: "AssayDilutionPlanSummary" },
    dependsOnProofRefs: ["assay.interaction.dilution-formula-summary-v1"], evidenceTypeIds: [], accessiblePathIds: [dilutionPathId],
    limitations: ["The semantic table presents every planned concentration and exact equation without implying observed experimental results."],
  },
  {
    id: "assay.model.exact-serial-dilution-v1",
    kind: "deterministic-model",
    title: "Exact serial-dilution concentration and conservation model",
    implementation: { source: "src/domain-packs/assay/dilution/engine.ts", exportName: "generateSerialDilutionPlan" },
    model: {
      deterministic: true,
      formula: "C_destination = C_source * V_transfer / (V_transfer + V_diluent); n_destination = C_destination * V_mixed; n_source_removed = n_terminal + n_discarded + rounding_residual",
      validityLimits: [
        "Concentrations use an explicit amount-per-volume basis and quantities are finite decimal strings in supported convertible units.",
        "The source must be mixed, every destination is mixed before transfer-out, and volumes must fit the declared device and available liquid.",
        "The first-release interaction path is limited to single-channel and eight-channel mappings on a canonical 96-well plate.",
        "Non-terminating results require an explicit decimal-place and tie-breaking policy; otherwise the plan is rejected.",
      ],
    },
    dependsOnProofRefs: ["assay.runtime.pipetting-v1", "assay.fixture.complete-96-well-dilution-plan-v1"],
    evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId, dilutionPathId],
    limitations: ["The model excludes stochastic accuracy, quantitative carryover, evaporation, non-ideal volume behavior, protocol QC, and calibration."],
  },
  {
    id: "assay.tests.exact-serial-dilution-v1",
    kind: "regression-test",
    title: "Exact plan and runtime complete-plate agreement regression",
    implementation: { source: "src/domain-packs/assay/__tests__/cycle07Integration.test.ts" },
    dependsOnProofRefs: ["assay.model.exact-serial-dilution-v1", "assay.tests.pipetting-runtime-v1"],
    evidenceTypeIds: [operationEvidenceId], accessiblePathIds: [pipettingPathId, dilutionPathId],
    limitations: ["Deterministic regression coverage establishes reproducibility, not calibration or protocol suitability."],
  },
  {
    id: "assay.tests.serial-dilution-properties-v1",
    kind: "regression-test",
    title: "Exact dilution conservation and feasibility property regressions",
    implementation: { source: "src/domain-packs/assay/dilution/__tests__/dilution.test.ts" },
    dependsOnProofRefs: ["assay.model.exact-serial-dilution-v1"],
    evidenceTypeIds: [], accessiblePathIds: [],
    limitations: ["Property cases test deterministic arithmetic boundaries and are not physical validation data."],
  },
  {
    id: "assay.fixture.explicit-qc-v1",
    kind: "representative-content-fixture",
    title: "Explicit synthetic control, replicate, and QC golden",
    implementation: { source: "src/domain-packs/assay/qc/__fixtures__/cycle08QcFixture.ts", exportName: "getCycle08QcGoldenFixture" },
    dependsOnProofRefs: [],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: [
      "The fixture thresholds and signals are explicitly source-controlled synthetic regression inputs.",
      "The fixture is not protocol calibration, clinical QC, XTT, or MIC evidence.",
    ],
  },
  {
    id: "assay.runtime.control-replicate-assignment-v1",
    kind: "runtime-handler",
    title: "Immutable control and replicate assignment actions",
    implementation: { source: "src/domain-packs/assay/qc/assignments.ts", exportName: "assignControlToWells" },
    dependsOnProofRefs: [],
    evidenceTypeIds: [assignmentEvidenceId],
    accessiblePathIds: [assignmentPathId],
    limitations: ["Assignment actions change explicit artifact metadata only and never infer scientific meaning."],
  },
  {
    id: "assay.validation.control-replicate-assignment-v1",
    kind: "validator",
    title: "Control and reciprocal replicate assignment validator",
    implementation: { source: "src/domain-packs/assay/qc/assignments.ts", exportName: "validateControlReplicateAssignments" },
    dependsOnProofRefs: ["assay.runtime.control-replicate-assignment-v1"],
    evidenceTypeIds: [],
    accessiblePathIds: [],
    limitations: ["Validation checks declared references, roles, counts, and reciprocal membership; it supplies no thresholds."],
  },
  {
    id: "assay.interaction.control-replicate-editor-v1",
    kind: "interaction-implementation",
    title: "Explicit control and replicate assignment editor",
    implementation: { source: "src/assay/controls/AssayControlReplicateEditor.tsx", exportName: "AssayControlReplicateEditor" },
    dependsOnProofRefs: ["assay.runtime.control-replicate-assignment-v1"],
    evidenceTypeIds: [assignmentEvidenceId],
    accessiblePathIds: [assignmentPathId],
    limitations: ["Native forms require authored IDs, roles, meanings, counts, aggregations, and well coordinates."],
  },
  {
    id: "assay.evidence.assignment-change-v1",
    kind: "evidence-producer",
    title: "Allowlisted assay assignment-change evidence",
    implementation: { source: "src/domain-packs/assay/qc/assignments.ts", exportName: "projectAssayAssignmentChange" },
    dependsOnProofRefs: ["assay.runtime.control-replicate-assignment-v1"],
    evidenceTypeIds: [assignmentEvidenceId],
    accessiblePathIds: [assignmentPathId],
    limitations: ["Assignment evidence records explicit artifact edits, not protocol acceptance or grading."],
  },
  {
    id: "assay.accessible.control-replicate-editor-v1",
    kind: "accessible-path",
    title: "Native keyboard and screen-reader control/replicate editor",
    implementation: { source: "src/assay/controls/AssayControlReplicateEditor.tsx", exportName: "AssayControlReplicateEditor" },
    dependsOnProofRefs: ["assay.interaction.control-replicate-editor-v1"],
    evidenceTypeIds: [assignmentEvidenceId],
    accessiblePathIds: [assignmentPathId],
    limitations: ["The table and live status text expose current counts and accepted/rejected changes without color-only state."],
  },
  {
    id: "assay.runtime.profile-configurable-qc-v1",
    kind: "runtime-handler",
    title: "Profile-configurable assay QC evaluator",
    implementation: { source: "src/domain-packs/assay/qc/engine.ts", exportName: "evaluateAssayQc" },
    dependsOnProofRefs: ["assay.fixture.explicit-qc-v1"],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: ["The evaluator returns indeterminate when prerequisites are absent and never supplies a global threshold."],
  },
  {
    id: "assay.validation.qc-contracts-v1",
    kind: "validator",
    title: "Observation, QC policy, and evaluation validators",
    implementation: { source: "src/domain-packs/assay/qc/validation.ts", exportName: "validateAssayQcRuleSet" },
    dependsOnProofRefs: ["assay.runtime.profile-configurable-qc-v1"],
    evidenceTypeIds: [],
    accessiblePathIds: [],
    limitations: ["Validation requires explicit policy source, thresholds, references, review state, and correction provenance."],
  },
  {
    id: "assay.interaction.qc-dashboard-v1",
    kind: "interaction-implementation",
    title: "Table-first assay QC dashboard",
    implementation: { source: "src/assay/results/AssayQcDashboard.tsx", exportName: "AssayQcDashboard" },
    dependsOnProofRefs: ["assay.runtime.profile-configurable-qc-v1"],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: ["The chart is supplementary; the table and formula trace are authoritative."],
  },
  {
    id: "assay.evidence.qc-bundle-trace-v1",
    kind: "evidence-producer",
    title: "Deterministic assay evidence bundle and semantic trace projection",
    implementation: { source: "src/domain-packs/assay/evidence/assembly.ts", exportName: "assembleAssayEvidence" },
    dependsOnProofRefs: ["assay.runtime.profile-configurable-qc-v1"],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: ["Only semantic allowlisted data is projected; raw images, runtime state, identity, and provider internals are excluded."],
  },
  {
    id: "assay.accessible.qc-chart-table-v1",
    kind: "accessible-path",
    title: "Assay QC chart/table parity and formula trace",
    implementation: { source: "src/assay/results/AssayQcDashboard.tsx", exportName: "AssayQcDashboard" },
    dependsOnProofRefs: ["assay.interaction.qc-dashboard-v1"],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: ["Status is expressed in text and every plotted point comes from the same authoritative table projection."],
  },
  {
    id: "assay.model.profile-configurable-qc-v1",
    kind: "deterministic-model",
    title: "Deterministic profile-configurable assay QC statistics",
    implementation: { source: "src/domain-packs/assay/qc/engine.ts", exportName: "evaluateAssayQc" },
    model: {
      deterministic: true,
      formula: "corrected = reviewed - blank_aggregate; normalized = configured(corrected / reference_mean); sample_sd = sqrt(sum((x - mean)^2)/(n-1)); CV = sample_sd/abs(mean)*100; Zprime = 1-3*(sd_high+sd_low)/abs(mean_high-mean_low)",
      validityLimits: [
        "Every observation has explicit source type, review status, provenance, well reference, decimal value, and unit.",
        "All thresholds, control references, well sets, severity, rounding, source/version, and validity statements are supplied by one validated rule set.",
        "Z-prime runs only when explicitly enabled, both control sets meet the configured minimum count, and their means differ.",
        "Outlier rules flag observations for review without removing them from aggregation.",
      ],
    },
    dependsOnProofRefs: ["assay.runtime.profile-configurable-qc-v1", "assay.fixture.explicit-qc-v1"],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: ["No protocol calibration, clinical acceptance, universal assay threshold, endpoint determination, or automatic deletion is claimed."],
  },
  {
    id: "assay.tests.controls-qc-v1",
    kind: "regression-test",
    title: "Control, replicate, QC statistics, and indeterminate-state regressions",
    implementation: { source: "src/domain-packs/assay/qc/__tests__/qc.test.ts" },
    dependsOnProofRefs: ["assay.model.profile-configurable-qc-v1", "assay.runtime.control-replicate-assignment-v1"],
    evidenceTypeIds: [assignmentEvidenceId, observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [assignmentPathId, qcPathId],
    limitations: ["Regression fixtures establish deterministic behavior only; they are not scientific calibration data."],
  },
  {
    id: "assay.tests.qc-evidence-accessibility-v1",
    kind: "regression-test",
    title: "QC evidence, trace, and accessible chart/table parity regressions",
    implementation: { source: "src/domain-packs/assay/evidence/__tests__/evidence.test.ts" },
    dependsOnProofRefs: ["assay.evidence.qc-bundle-trace-v1", "assay.accessible.qc-chart-table-v1"],
    evidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [qcPathId],
    limitations: ["Source coverage is not a protocol or browser release gate."],
  },
  {
    id: "assay.fixture.operational-planning-v1",
    kind: "representative-content-fixture",
    title: "Explicit 96-well operational-planning golden",
    implementation: { source: "src/domain-packs/assay/planning/__fixtures__/cycle09PlanningFixture.ts", exportName: "getCycle09AssayPlanningFixture" },
    dependsOnProofRefs: [],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["Every amount, duration, and capacity is a source-controlled synthetic regression input, not a protocol or purchasing recommendation."],
  },
  {
    id: "assay.runtime.operational-planner-v1",
    kind: "runtime-handler",
    title: "Assay operation-to-resource planner",
    implementation: { source: "src/domain-packs/assay/planning/planner.ts", exportName: "planAssayRun" },
    dependsOnProofRefs: ["assay.fixture.operational-planning-v1"],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["The planner requires an accepted operation graph and explicit planning metadata; missing metadata remains blocking."],
  },
  {
    id: "assay.validation.operational-planning-v1",
    kind: "validator",
    title: "Versioned assay planning-profile validator",
    implementation: { source: "src/domain-packs/assay/planning/validation.ts", exportName: "validateAssayPlanningProfile" },
    dependsOnProofRefs: ["assay.runtime.operational-planner-v1"],
    evidenceTypeIds: [],
    accessiblePathIds: [],
    limitations: ["Validation checks declared metadata and references; it does not certify local protocol, safety, or capacity suitability."],
  },
  {
    id: "assay.interaction.operational-planner-v1",
    kind: "interaction-implementation",
    title: "Assay materials and operational-plan review",
    implementation: { source: "src/assay/planning/AssayRunPlanner.tsx", exportName: "AssayRunPlanner" },
    dependsOnProofRefs: ["assay.runtime.operational-planner-v1"],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["Native controls edit declared context and profile assumptions; exports are review-only and perform no external action."],
  },
  {
    id: "assay.evidence.operational-plan-v1",
    kind: "evidence-producer",
    title: "Allowlisted assay run-plan summary projection",
    implementation: { source: "src/domain-packs/assay/planning/planner.ts", exportName: "projectAssayRunPlanEvidence" },
    dependsOnProofRefs: ["assay.runtime.operational-planner-v1"],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["The summary contains plan status, requirement count, and limitations; it excludes runtime state, identity, provider data, and purchase actions."],
  },
  {
    id: "assay.accessible.operational-plan-v1",
    kind: "accessible-path",
    title: "Semantic material, formula, shortage, and schedule review",
    implementation: { source: "src/assay/planning/AssayRunPlanner.tsx", exportName: "AssayRunPlanner" },
    dependsOnProofRefs: ["assay.interaction.operational-planner-v1"],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["Status and bottlenecks are textual; requirement, formula, and schedule details use semantic tables and native disclosures."],
  },
  {
    id: "assay.model.operational-planning-v1",
    kind: "deterministic-model",
    title: "Exact assay resource, batch, and capacity model",
    implementation: { source: "src/domain-packs/assay/planning/planner.ts", exportName: "planAssayRun" },
    model: {
      deterministic: true,
      formula: "liquid = operation_consumption * plate_runs; prepared = liquid * (1 + overage_percent/100) + dead_volume * batch_count; tips = sum(attach_tip_channels) * plate_runs; waves = ceil(plate_runs/(units_available*plate_slots_per_wave))",
      validityLimits: [
        "The operation graph is accepted by the assay runtime and uses registered pipette and tip definitions.",
        "Every external source, package size, consumable count, master-mix component, overage, dead volume, duration, and capacity is explicit versioned profile or user-declared data.",
        "One operation graph is executed per group, repeat, and technical-replicate plate run.",
        "All quantities use supported exact-decimal units and inventory comparison requires compatible units.",
      ],
    },
    dependsOnProofRefs: ["assay.runtime.operational-planner-v1", "assay.fixture.operational-planning-v1"],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["The model is operational arithmetic, not protocol calibration, safety review, purchasing execution, or automation-system scheduling."],
  },
  {
    id: "assay.tests.operational-planning-v1",
    kind: "regression-test",
    title: "Assay tip, liquid, batch, inventory, capacity, and export regressions",
    implementation: { source: "src/domain-packs/assay/planning/__tests__/planning.test.ts" },
    dependsOnProofRefs: ["assay.model.operational-planning-v1", "assay.accessible.operational-plan-v1"],
    evidenceTypeIds: [runPlanEvidenceId],
    accessiblePathIds: [planningPathId],
    limitations: ["Source regression coverage proves deterministic contract behavior only; detailed tests were not executed under the repository validation policy."],
  },
  {
    id: "assay.fixture.observation-ingestion-v1",
    kind: "representative-content-fixture",
    title: "Explicit CSV and Assay Lens ingestion fixtures",
    implementation: { source: "src/domain-packs/assay/ingestion/__fixtures__/cycle10IngestionFixture.ts", exportName: "cycle10AssayLensObservationPackage" },
    dependsOnProofRefs: [],
    evidenceTypeIds: [ingestedObservationEvidenceId],
    accessiblePathIds: [ingestionPathId],
    limitations: ["Fixture values are synthetic file-interoperability inputs, not plate-reader, absorbance, protocol, or calibration evidence."],
  },
  {
    id: "assay.runtime.observation-review-v1",
    kind: "runtime-handler",
    title: "Transactional external observation review",
    implementation: { source: "src/domain-packs/assay/ingestion/review.ts", exportName: "commitObservationReview" },
    dependsOnProofRefs: ["assay.fixture.observation-ingestion-v1"],
    evidenceTypeIds: [ingestedObservationEvidenceId],
    accessiblePathIds: [ingestionPathId],
    limitations: ["Only explicitly accepted or corrected values are eligible for downstream QC; rejected values remain provenance records."],
  },
  {
    id: "assay.validation.observation-ingestion-v1",
    kind: "validator",
    title: "CSV, file-boundary, and Assay Lens v1 validators",
    implementation: { source: "src/domain-packs/assay/ingestion/schema.ts", exportName: "validateAssayLensObservationPackage" },
    dependsOnProofRefs: ["assay.runtime.observation-review-v1"],
    evidenceTypeIds: [],
    accessiblePathIds: [],
    limitations: ["Validation enforces explicit orientation, coordinate, unit, channel, provenance, size, MIME, version, and forbidden-data boundaries without inferring scientific meaning."],
  },
  {
    id: "assay.interaction.observation-import-review-v1",
    kind: "interaction-implementation",
    title: "CSV, manual, image-review, and Assay Lens file workflow",
    implementation: { source: "src/assay/import/AssayObservationImportReview.tsx", exportName: "AssayObservationImportReview" },
    dependsOnProofRefs: ["assay.runtime.observation-review-v1"],
    evidenceTypeIds: [ingestedObservationEvidenceId],
    accessiblePathIds: [ingestionPathId],
    limitations: ["The image preview is transient and manual; Assay Studio performs no built-in computer vision and the network bridge remains disabled."],
  },
  {
    id: "assay.evidence.ingested-observation-v1",
    kind: "evidence-producer",
    title: "Allowlisted reviewed-ingestion evidence",
    implementation: { source: "src/domain-packs/assay/ingestion/evidence.ts", exportName: "projectIngestedObservationEvidence" },
    dependsOnProofRefs: ["assay.runtime.observation-review-v1"],
    evidenceTypeIds: [ingestedObservationEvidenceId],
    accessiblePathIds: [ingestionPathId],
    limitations: ["Evidence preserves source type, review state, method/version, confidence, flags, and correction reference while excluding image pixels, paths, EXIF, hashes, and provider internals."],
  },
  {
    id: "assay.accessible.observation-import-review-v1",
    kind: "accessible-path",
    title: "Native mapping controls and semantic observation review table",
    implementation: { source: "src/assay/import/AssayObservationImportReview.tsx", exportName: "AssayObservationImportReview" },
    dependsOnProofRefs: ["assay.interaction.observation-import-review-v1"],
    evidenceTypeIds: [ingestedObservationEvidenceId],
    accessiblePathIds: [ingestionPathId],
    limitations: ["Mapping, review state, correction inputs, diagnostics, and source labels are available through native controls and a semantic table without color-only status."],
  },
  {
    id: "assay.tests.observation-ingestion-v1",
    kind: "regression-test",
    title: "CSV, Assay Lens, security, review-gate, and accessibility regressions",
    implementation: { source: "src/domain-packs/assay/ingestion/__tests__/ingestion.test.ts" },
    dependsOnProofRefs: ["assay.validation.observation-ingestion-v1", "assay.accessible.observation-import-review-v1"],
    evidenceTypeIds: [ingestedObservationEvidenceId],
    accessiblePathIds: [ingestionPathId],
    limitations: ["Regression source establishes intended deterministic contract behavior only; detailed tests are not executed under the repository validation policy."],
  },
  {
    id: "assay.fixture.protocol-workflows-v1",
    kind: "representative-content-fixture",
    title: "Synthetic XTT and broth-microdilution golden workflows",
    implementation: { source: "src/domain-packs/assay/profiles/__fixtures__/cycle11ProtocolFixtures.ts", exportName: "getCycle11ProtocolGoldenWorkflows" },
    dependsOnProofRefs: ["assay.fixture.observation-ingestion-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["All observations, concentrations, and results are source-controlled synthetic examples; they are not clinical, calibrated, or wet-lab validation data."],
  },
  {
    id: "assay.runtime.protocol-analysis-v1",
    kind: "runtime-handler",
    title: "Checked profile-bound assay analysis",
    implementation: { source: "src/domain-packs/assay/profiles/analysis.ts", exportName: "analyzeXttMetabolicActivity" },
    dependsOnProofRefs: ["assay.fixture.protocol-workflows-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["Analysis accepts only reviewed observations and exact checked profile versions; unmet prerequisites return indeterminate."],
  },
  {
    id: "assay.validation.protocol-profile-v1",
    kind: "validator",
    title: "Protocol profile and result validators",
    implementation: { source: "src/domain-packs/assay/profiles/registry.ts", exportName: "validateAssayProtocolProfile" },
    dependsOnProofRefs: ["assay.fixture.protocol-workflows-v1"],
    evidenceTypeIds: [],
    accessiblePathIds: [],
    limitations: ["Profile validation rejects version drift, dangling metric references, forbidden data, and XTT profiles without explicit control roles."],
  },
  {
    id: "assay.interaction.protocol-analysis-v1",
    kind: "interaction-implementation",
    title: "Checked profile and result review",
    implementation: { source: "src/assay/results/AssayProtocolAnalysisPanel.tsx", exportName: "AssayProtocolAnalysisPanel" },
    dependsOnProofRefs: ["assay.runtime.protocol-analysis-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["The selector switches explicit source-controlled examples and never infers a protocol for an open draft."],
  },
  {
    id: "assay.evidence.protocol-analysis-v1",
    kind: "evidence-producer",
    title: "Profile-bound normalized result and formula projection",
    implementation: { source: "src/domain-packs/assay/profiles/analysis.ts", exportName: "analyzeXttMetabolicActivity" },
    dependsOnProofRefs: ["assay.runtime.protocol-analysis-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["Results preserve profile, data-source, control, formula, limitation, and endpoint terminology without clinical fields."],
  },
  {
    id: "assay.accessible.protocol-analysis-v1",
    kind: "accessible-path",
    title: "Table-first checked profile and endpoint review",
    implementation: { source: "src/assay/results/AssayProtocolAnalysisPanel.tsx", exportName: "AssayProtocolAnalysisPanel" },
    dependsOnProofRefs: ["assay.interaction.protocol-analysis-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["Profile identity, sources, status, boundaries, rows, endpoint, diagnostics, and formulas are textual and keyboard accessible."],
  },
  {
    id: "assay.model.protocol-analysis-v1",
    kind: "deterministic-model",
    title: "Safe exact protocol analysis rules",
    implementation: { source: "src/domain-packs/assay/profiles/evaluator.ts", exportName: "evaluateAssayExpression" },
    model: {
      deterministic: true,
      formula: "Checked arithmetic AST for blank/reference normalization; ordered exact concentration comparison for endpoint selection.",
      validityLimits: [
        "One checked immutable profile version and reviewed observations using one profile-allowed readout mapping.",
        "XTT requires explicit blank/reference controls and a nonzero corrected reference.",
        "Broth microdilution requires valid growth/sterility controls, explicit concentrations, replicate agreement, and monotonic outcomes.",
      ],
    },
    dependsOnProofRefs: ["assay.validation.protocol-profile-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["No arbitrary code, curve fitting, IC50, clinical breakpoint, susceptibility category, or universal scientific constant is evaluated."],
  },
  {
    id: "assay.tests.protocol-analysis-v1",
    kind: "regression-test",
    title: "Protocol profile, terminology, endpoint, indeterminate, and UI regressions",
    implementation: { source: "src/domain-packs/assay/profiles/__tests__/profiles.test.ts" },
    dependsOnProofRefs: ["assay.model.protocol-analysis-v1", "assay.accessible.protocol-analysis-v1"],
    evidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
    accessiblePathIds: [protocolAnalysisPathId],
    limitations: ["Regression source records expected behavior; detailed tests are intentionally not executed under repository policy."],
  },
];

const pipettingProofRefs: CapabilityProofRef[] = [
  proofRef("assay.runtime.pipetting-v1", "runtime-handler"),
  proofRef("assay.interaction.pipetting-workbench-v1", "interaction-implementation"),
  proofRef("assay.validation.pipetting-operation-v1", "validator"),
  proofRef("assay.evidence.pipetting-operation-v1", "evidence-producer"),
  proofRef("assay.accessible.pipetting-workbench-v1", "accessible-path"),
  proofRef("assay.tests.pipetting-runtime-v1", "regression-test"),
  proofRef("assay.tests.pipetting-workbench-v1", "regression-test"),
];

const pipettingOperations = [
  { id: "select-pipette", title: "Select assay pipette", outcome: "Select a registered single-channel or eight-channel pipette through the shared assay runtime." },
  { id: "set-volume", title: "Set pipette volume", outcome: "Set an exact nominal pipette volume within the registered range and increment." },
  { id: "attach-tips", title: "Attach compatible tips", outcome: "Attach mutually compatible tips to every active pipette channel." },
  { id: "aspirate", title: "Aspirate assay liquid", outcome: "Aspirate exact nominal volume from a mixed, sufficiently filled source using explicit single- or eight-channel mapping." },
  { id: "dispense", title: "Dispense assay liquid", outcome: "Dispense loaded channels into capacity-valid wells while conserving component volume and contamination tags." },
  { id: "mix", title: "Mix assay wells", outcome: "Mix capacity-valid wells through an explicit nominal-volume, cycle-counted operation without changing well volume." },
  { id: "eject-tips", title: "Eject empty tips", outcome: "Eject attached tips only after loaded liquid has been dispensed or explicitly discarded." },
] as const;

const assignmentProofRefs: CapabilityProofRef[] = [
  proofRef("assay.runtime.control-replicate-assignment-v1", "runtime-handler"),
  proofRef("assay.validation.control-replicate-assignment-v1", "validator"),
  proofRef("assay.interaction.control-replicate-editor-v1", "interaction-implementation"),
  proofRef("assay.evidence.assignment-change-v1", "evidence-producer"),
  proofRef("assay.accessible.control-replicate-editor-v1", "accessible-path"),
  proofRef("assay.tests.controls-qc-v1", "regression-test"),
];

const qcProofRefs: CapabilityProofRef[] = [
  proofRef("assay.fixture.explicit-qc-v1", "representative-content-fixture"),
  proofRef("assay.runtime.profile-configurable-qc-v1", "runtime-handler"),
  proofRef("assay.validation.qc-contracts-v1", "validator"),
  proofRef("assay.interaction.qc-dashboard-v1", "interaction-implementation"),
  proofRef("assay.evidence.qc-bundle-trace-v1", "evidence-producer"),
  proofRef("assay.accessible.qc-chart-table-v1", "accessible-path"),
  proofRef("assay.model.profile-configurable-qc-v1", "deterministic-model"),
  proofRef("assay.tests.controls-qc-v1", "regression-test"),
  proofRef("assay.tests.qc-evidence-accessibility-v1", "regression-test"),
];

const planningProofRefs: CapabilityProofRef[] = [
  proofRef("assay.fixture.operational-planning-v1", "representative-content-fixture"),
  proofRef("assay.runtime.operational-planner-v1", "runtime-handler"),
  proofRef("assay.validation.operational-planning-v1", "validator"),
  proofRef("assay.interaction.operational-planner-v1", "interaction-implementation"),
  proofRef("assay.evidence.operational-plan-v1", "evidence-producer"),
  proofRef("assay.accessible.operational-plan-v1", "accessible-path"),
  proofRef("assay.model.operational-planning-v1", "deterministic-model"),
  proofRef("assay.tests.operational-planning-v1", "regression-test"),
];

const ingestionProofRefs: CapabilityProofRef[] = [
  proofRef("assay.fixture.observation-ingestion-v1", "representative-content-fixture"),
  proofRef("assay.runtime.observation-review-v1", "runtime-handler"),
  proofRef("assay.validation.observation-ingestion-v1", "validator"),
  proofRef("assay.interaction.observation-import-review-v1", "interaction-implementation"),
  proofRef("assay.evidence.ingested-observation-v1", "evidence-producer"),
  proofRef("assay.accessible.observation-import-review-v1", "accessible-path"),
  proofRef("assay.tests.observation-ingestion-v1", "regression-test"),
];

const protocolAnalysisProofRefs: CapabilityProofRef[] = [
  proofRef("assay.fixture.protocol-workflows-v1", "representative-content-fixture"),
  proofRef("assay.runtime.protocol-analysis-v1", "runtime-handler"),
  proofRef("assay.validation.protocol-profile-v1", "validator"),
  proofRef("assay.interaction.protocol-analysis-v1", "interaction-implementation"),
  proofRef("assay.evidence.protocol-analysis-v1", "evidence-producer"),
  proofRef("assay.accessible.protocol-analysis-v1", "accessible-path"),
  proofRef("assay.model.protocol-analysis-v1", "deterministic-model"),
  proofRef("assay.tests.protocol-analysis-v1", "regression-test"),
];

const pipettingEntries: CapabilityEntry[] = pipettingOperations.map((operation) => ({
  ref: ref("operation", `operation.${operation.id}`),
  title: operation.title,
  summary: operation.outcome,
  tags: ["assay", "pipetting", "runtime", operation.id],
  claims: [{
    id: "interactive",
    outcome: operation.outcome,
    maximumFidelity: "F2",
    proofRefs: pipettingProofRefs,
    requiredEvidenceTypeIds: [operationEvidenceId],
    requiredAccessiblePathIds: [pipettingPathId],
  }],
  dependencies: [],
  accessiblePathIds: [pipettingPathId],
  exampleIds: [],
  limitations: [
    "The operation uses nominal deterministic quantities and registered equipment definitions.",
    "No hardware-control, stochastic-accuracy, quantitative-carryover, or protocol-QC claim is made.",
  ],
}));

const entries: CapabilityEntry[] = [
  {
    ref: ref("object", "plate.96-well-layout"),
    title: "96-well plate layout",
    summary: "Represent a canonical A1-top-left 8 by 12 plate with visible coordinates, roles, labels, and table parity.",
    tags: ["assay", "plate", "96-well", "layout"],
    claims: [{
      id: "represented",
      outcome: "Display, inspect, select, and author a canonical 96-well plate layout through synchronized grid and table representations.",
      maximumFidelity: "F1",
      proofRefs: [
        proofRef("assay.fixture.layout-v1", "representative-content-fixture"),
        proofRef("assay.validation.artifact-v1", "validator"),
        proofRef("assay.view.plate-editor-v1", "interaction-implementation"),
        proofRef("assay.accessible.plate-grid-table-v1", "accessible-path"),
      ],
      requiredEvidenceTypeIds: [], requiredAccessiblePathIds: [platePathId],
    }],
    dependencies: [], accessiblePathIds: [platePathId], exampleIds: [],
    limitations: ["F1 representation only; the layout itself does not prove measurement, QC, or analysis behavior."],
  },
  {
    ref: ref("operation", "operation.schema-scaffold"),
    title: "AssayDefinition operation schema scaffold",
    summary: "Store reviewed AssayDefinition operation vocabulary without claiming compilation to the Cycle 07 runtime.",
    tags: ["assay", "operation", "schema", "instructional"],
    claims: [{
      id: "instructional",
      outcome: "Include reviewed, structurally validated AssayDefinition operation definitions for later compilation.",
      maximumFidelity: "F0",
      proofRefs: [proofRef("assay.fixture.layout-v1", "representative-content-fixture")],
      requiredEvidenceTypeIds: [], requiredAccessiblePathIds: [],
    }],
    dependencies: [], accessiblePathIds: [], exampleIds: [],
    limitations: ["This F0 claim is distinct from the separately validated and executable assay-studio.operation runtime contract."],
  },
  ...pipettingEntries,
  {
    ref: ref("interaction", "interaction.control-replicate-assignment"),
    title: "Explicit control and replicate assignment",
    summary: "Author validated control roles and reciprocal replicate membership through native accessible forms.",
    tags: ["assay", "controls", "replicates", "authoring", "accessible"],
    claims: [{
      id: "interactive",
      outcome: "Create or update explicit control definitions and reciprocal replicate groups, then assign them to named wells without inferred scientific metadata.",
      maximumFidelity: "F2",
      proofRefs: assignmentProofRefs,
      requiredEvidenceTypeIds: [assignmentEvidenceId],
      requiredAccessiblePathIds: [assignmentPathId],
    }],
    dependencies: [ref("object", "plate.96-well-layout")],
    accessiblePathIds: [assignmentPathId],
    exampleIds: [],
    limitations: [
      "The editor does not infer required controls, replicate counts, aggregation policies, or scientific meanings.",
      "Protocol-specific requirements remain versioned QC/profile data.",
    ],
  },
  {
    ref: ref("model", "model.profile-configurable-qc"),
    title: "Profile-configurable assay QC",
    summary: "Evaluate reviewed observations with explicit blank correction, normalization, replicate statistics, control separation, optional Z-prime, edge/drift warnings, and review-only outlier flags.",
    tags: ["assay", "qc", "controls", "replicates", "statistics", "evidence"],
    claims: [{
      id: "quantitative",
      outcome: "Produce deterministic rule results, formula traces, table/chart projections, evidence bundles, and a semantic trace from reviewed observations and one explicit versioned QC rule set.",
      maximumFidelity: "F3",
      validityRange: {
        observations: "reviewed decimal observations with explicit well, unit, source type, and provenance",
        rules: "validated versioned rule data with explicit source, references, thresholds, severities, rounding, validity range, and limitations",
        controls: "uniquely identified assay controls with the configured minimum observed wells",
        statistics: "sample SD/CV require at least two reviewed values and nonzero mean for CV; optional Z-prime requires distinct control means",
      },
      proofRefs: qcProofRefs,
      requiredEvidenceTypeIds: [observationEvidenceId, qcEvidenceId, normalizedEvidenceId, formulaTraceEvidenceId],
      requiredAccessiblePathIds: [qcPathId],
    }],
    dependencies: [
      ref("object", "plate.96-well-layout"),
      ref("interaction", "interaction.control-replicate-assignment"),
    ],
    accessiblePathIds: [qcPathId],
    exampleIds: [],
    limitations: [
      "Thresholds are never global constants and missing prerequisites produce indeterminate, not pass.",
      "Outliers are flagged without automatic deletion.",
      "No endpoint, XTT, MIC, clinical QC, or F4 calibration claim is made.",
    ],
  },
  {
    ref: ref("model", "model.exact-serial-dilution"),
    title: "Exact serial dilution",
    summary: "Generate a deterministic factor- or target-derived serial-dilution plan with explicit mappings, formula traces, and conservation totals.",
    tags: ["assay", "dilution", "exact-decimal", "quantitative", "96-well"],
    claims: [{
      id: "quantitative",
      outcome: "Generate and rehearse an exact single- or eight-channel serial dilution whose formula traces reproduce concentration, volume, retained analyte, and discard totals.",
      maximumFidelity: "F3",
      validityRange: {
        source: "mixed source with positive available volume and explicit amount-per-volume concentration basis",
        series: "factor greater than one or explicit non-increasing concentration targets within declared tolerance",
        transfer: "positive exact-decimal volumes within device range, increment, liquid availability, and well capacity",
        mapping: "single-channel or eight-channel explicit mapping on a canonical 96-well plate",
      },
      proofRefs: [
        ...pipettingProofRefs,
        proofRef("assay.fixture.complete-96-well-dilution-plan-v1", "representative-content-fixture"),
        proofRef("assay.interaction.dilution-formula-summary-v1", "interaction-implementation"),
        proofRef("assay.accessible.dilution-formula-summary-v1", "accessible-path"),
        proofRef("assay.model.exact-serial-dilution-v1", "deterministic-model"),
        proofRef("assay.tests.exact-serial-dilution-v1", "regression-test"),
        proofRef("assay.tests.serial-dilution-properties-v1", "regression-test"),
      ],
      requiredEvidenceTypeIds: [operationEvidenceId], requiredAccessiblePathIds: [pipettingPathId, dilutionPathId],
    }],
    dependencies: [ref("operation", "operation.aspirate"), ref("operation", "operation.dispense"), ref("operation", "operation.mix")],
    accessiblePathIds: [pipettingPathId, dilutionPathId], exampleIds: [],
    limitations: [
      "This is a deterministic nominal model, not a device calibration or physical accuracy claim.",
      "Stochastic error, quantitative carryover, evaporation, non-ideal volumes, plate reading, protocol QC, and result interpretation remain unclaimed.",
    ],
  },
  {
    ref: ref("interaction", "interaction.observation-ingestion"),
    title: "Reviewed external assay observation ingestion",
    summary: "Map long or matrix CSV, review manual/image-derived observations, and exchange versioned Assay Lens request/result files through one explicit transaction.",
    tags: ["assay", "ingestion", "csv", "assay-lens", "review", "provenance"],
    claims: [{
      id: "interactive",
      outcome: "Deterministically map external scalar observations and commit only explicitly accepted or corrected values with source, method, confidence, flags, and correction provenance.",
      maximumFidelity: "F2",
      validityRange: {
        plate: "canonical 96-well A1-top-left orientation with explicit plate identifier",
        csv: "bounded UTF-8 long or matrix input with explicit delimiter, decimal separator, coordinate, channel, and unit mapping",
        image: "manual browser-local review or validated assay-lens.observation-package v1 file import; no built-in vision",
        review: "every mapped value explicitly accepted, corrected, or rejected before transaction commit",
      },
      proofRefs: ingestionProofRefs,
      requiredEvidenceTypeIds: [ingestedObservationEvidenceId],
      requiredAccessiblePathIds: [ingestionPathId],
    }],
    dependencies: [ref("object", "plate.96-well-layout")],
    accessiblePathIds: [ingestionPathId],
    exampleIds: [],
    limitations: [
      "Image-derived intensity is not assumed equivalent to absorbance or instrument-exported signal.",
      "No arbitrary URL fetch, remote bridge, automatic image acceptance, endpoint analysis, clinical interpretation, or F4 calibration is performed or claimed.",
    ],
  },
  {
    ref: ref("planning", "planning.operational-run"),
    title: "Assay materials and operational run planning",
    summary: "Project an accepted assay operation graph into exact consumables, liquids, master-mix batches, inventory shortages, instrument waves, operational phases, formula traces, and review-only exports.",
    tags: ["assay", "planning", "materials", "capacity", "inventory", "exact-decimal"],
    claims: [{
      id: "quantitative",
      outcome: "Produce a deterministic reviewable assay run plan from explicit operation, profile, grouping, inventory, capacity, overage, dead-volume, batch, and timing inputs.",
      maximumFidelity: "F3",
      validityRange: {
        operationGraph: "accepted assay-studio.operation v1 sequence using registered pipette and tip definitions",
        planningProfile: "validated assay-studio.planning-profile v1 with explicit source, validity, assumptions, limitations, and review flags",
        runContext: "positive classroom or research-planning groups, repeats, technical-replicate plate runs, inventory, stations, instrument capacities, and time windows",
        outputs: "nominal exact-decimal requirements, formula traces, shortages, batches, capacity waves, and non-ordering CSV/checklist exports",
      },
      proofRefs: planningProofRefs,
      requiredEvidenceTypeIds: [runPlanEvidenceId],
      requiredAccessiblePathIds: [planningPathId],
    }],
    dependencies: [
      ref("object", "plate.96-well-layout"),
      ref("operation", "operation.attach-tips"),
      ref("operation", "operation.aspirate"),
    ],
    accessiblePathIds: [planningPathId],
    exampleIds: [],
    limitations: [
      "No missing amount, threshold, timing, capacity, or local policy is guessed.",
      "No purchase, reservation, substitution, inventory mutation, safety approval, hardware control, clinical interpretation, or F4 calibration is performed or claimed.",
    ],
  },
  {
    ref: ref("model", "model.xtt-metabolic-activity"),
    title: "Profile-bound XTT metabolic-activity analysis",
    summary: "Calculate blank/reference-normalized metabolic activity and inhibition through a checked safe expression AST.",
    tags: ["assay", "xtt", "metabolic-activity", "profile", "non-clinical"],
    claims: [{
      id: "quantitative",
      outcome: "Produce deterministic percent metabolic activity/inhibition, replicate summaries, source labels, and formula traces from reviewed observations under one checked XTT profile.",
      maximumFidelity: "F3",
      validityRange: {
        profile: "assay.profile.xtt-metabolic-activity@1.0.0",
        data: "reviewed observations from one explicit profile-allowed unit and channel",
        controls: "explicit blank and positive-reference roles with reference mean greater than blank mean",
        interpretation: "protocol-dependent metabolic-activity proxy only",
      },
      proofRefs: protocolAnalysisProofRefs,
      requiredEvidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
      requiredAccessiblePathIds: [protocolAnalysisPathId],
    }],
    dependencies: [ref("interaction", "interaction.observation-ingestion"), ref("interaction", "interaction.control-replicate-assignment")],
    accessiblePathIds: [protocolAnalysisPathId],
    exampleIds: [],
    limitations: [
      "XTT is represented only as a protocol-dependent metabolic-activity proxy, never a direct cell count.",
      "No universal wavelength, incubation, threshold, signal range, or clinical interpretation is supplied.",
    ],
  },
  {
    ref: ref("model", "model.broth-microdilution-endpoint"),
    title: "Profile-bound educational broth-microdilution endpoint",
    summary: "Select the lowest reviewed monotonic no-growth concentration only when profile controls and replicates are valid.",
    tags: ["assay", "broth-microdilution", "endpoint", "education", "non-clinical"],
    claims: [{
      id: "quantitative",
      outcome: "Produce a deterministic profile-bound educational endpoint or an explicit indeterminate result without clinical categories or advice.",
      maximumFidelity: "F3",
      validityRange: {
        profile: "assay.profile.educational-broth-microdilution@1.0.0",
        data: "reviewed profile-coded binary growth observations",
        controls: "valid growth and sterility controls",
        series: "explicit single-unit concentrations, replicate agreement, and monotonic growth/no-growth outcomes",
      },
      proofRefs: protocolAnalysisProofRefs,
      requiredEvidenceTypeIds: [normalizedEvidenceId, formulaTraceEvidenceId],
      requiredAccessiblePathIds: [protocolAnalysisPathId],
    }],
    dependencies: [ref("interaction", "interaction.observation-ingestion"), ref("model", "model.exact-serial-dilution")],
    accessiblePathIds: [protocolAnalysisPathId],
    exampleIds: [],
    limitations: [
      "No clinical breakpoint, S/I/R category, treatment advice, organism/drug auto-selection, or standards-conformity claim is produced.",
      "Invalid controls, conflicting replicates, missing concentrations, or non-monotonic results are indeterminate.",
    ],
  },
  {
    ref: ref("export", "export.release-review-package"),
    title: "Validated assay release review package",
    summary: "Validate, semantically compare, transactionally apply, and export a 96-well assay definition, sanitized package, plate-map CSV, and explicit release-limit report.",
    tags: ["assay", "validation", "compare", "export", "mcp", "accessibility"],
    claims: [{
      id: "representational",
      outcome: "Produce inspectable, sanitized assay release artifacts through the same pure services used by the direct app and six assaystudio MCP tools.",
      maximumFidelity: "F1",
      proofRefs: [
        proofRef("assay.release.shared-services-v1", "validator"),
        proofRef("assay.release.review-ui-v1", "interaction-implementation"),
        proofRef("assay.release.accessible-review-v1", "accessible-path"),
        proofRef("assay.release.tests-v1", "regression-test"),
      ],
      requiredEvidenceTypeIds: [],
      requiredAccessiblePathIds: [releaseReviewPathId],
    }],
    dependencies: [ref("object", "plate.96-well-layout")],
    accessiblePathIds: [releaseReviewPathId],
    exampleIds: [],
    limitations: [
      "The release decision is limited because detailed tests, browser checks, and formative review were not executed under repository policy.",
      "Exports do not add calibration, clinical interpretation, safety approval, hardware action, purchasing, persistence, or student data.",
    ],
  },
];

export const getAssayCapabilityManifestFragment = (): CapabilityManifestFragment => structuredClone({
  schema: "studio.capability-manifest-fragment",
  schemaVersion: "2.0",
  studioCoreVersion: "1.0.0",
  domainPack: {
    id: "assay", version, title: "Assay Studio",
    limitations: [
      "Cycle 12 adds shared direct-app release services, semantic compare/apply, reviewable exports, and six stateless assaystudio MCP tools.",
      "The release decision remains limited because detailed automated, browser, and formative-review execution is intentionally unrun under repository policy.",
      "Assessment, remote Assay Lens transport, clinical interpretation, and universal protocol constants remain unclaimed.",
      "No assay capability is F4 because no named calibration or protocol-profile evidence is registered.",
    ],
  },
  entries,
  proofs,
  accessiblePaths: [
    {
      id: platePathId,
      title: "Semantic plate grid with accessible table parity",
      modes: ["keyboard", "pointer", "screen-reader"],
      implementation: { source: "src/assay/AssayPlateEditor.tsx", exportName: "AssayPlateEditor" },
      limitations: ["This path covers plate-map selection and authored role/label review."],
    },
    {
      id: pipettingPathId,
      title: "Accessible pipetting rehearsal",
      modes: ["keyboard", "pointer", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/player/AssayPipettingRehearsal.tsx", exportName: "AssayPipettingWorkbench" },
      limitations: ["Native controls dispatch the same typed intents; hardware control and protocol-specific QC are not claimed."],
    },
    {
      id: dilutionPathId,
      title: "Semantic exact dilution formula-trace table",
      modes: ["keyboard", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/player/AssayDilutionPlanSummary.tsx", exportName: "AssayDilutionPlanSummary" },
      limitations: ["The table reports generated nominal values and conservation, not measured plate-reader results or protocol QC."],
    },
    {
      id: assignmentPathId,
      title: "Explicit control and replicate assignment forms",
      modes: ["keyboard", "pointer", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/controls/AssayControlReplicateEditor.tsx", exportName: "AssayControlReplicateEditor" },
      limitations: ["Native forms require explicit authored metadata and report accepted/rejected assignment state in text and tables."],
    },
    {
      id: qcPathId,
      title: "Table-first QC results with supplementary chart",
      modes: ["keyboard", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/results/AssayQcDashboard.tsx", exportName: "AssayQcDashboard" },
      limitations: ["The table and formula trace are authoritative; status is textual and the chart is supplementary."],
    },
    {
      id: planningPathId,
      title: "Semantic assay materials, formulas, shortages, and schedule review",
      modes: ["keyboard", "pointer", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/planning/AssayRunPlanner.tsx", exportName: "AssayRunPlanner" },
      limitations: ["Native controls update declared inputs; semantic tables and downloadable text exports remain review-only and perform no external action."],
    },
    {
      id: ingestionPathId,
      title: "Accessible observation mapping and explicit review",
      modes: ["keyboard", "pointer", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/import/AssayObservationImportReview.tsx", exportName: "AssayObservationImportReview" },
      limitations: ["Native mapping controls and a semantic table expose source, method, confidence, diagnostics, correction input, and textual review status."],
    },
    {
      id: protocolAnalysisPathId,
      title: "Checked profile, source, result, endpoint, and formula tables",
      modes: ["keyboard", "pointer", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/results/AssayProtocolAnalysisPanel.tsx", exportName: "AssayProtocolAnalysisPanel" },
      limitations: ["The selector changes explicit examples only; scientific boundaries, sources, status, limitations, and tables remain visible in text."],
    },
    {
      id: releaseReviewPathId,
      title: "Assay validation, semantic compare/apply, and downloadable release review",
      modes: ["keyboard", "pointer", "screen-reader", "accessible-process"],
      implementation: { source: "src/assay/release/AssayReleaseReview.tsx", exportName: "AssayReleaseReview" },
      limitations: ["Native controls and semantic tables expose validation and changes; detailed browser execution remains intentionally unrun."],
    },
  ],
  compatibilityEdges: [
    { from: ref("model", "model.exact-serial-dilution"), to: ref("operation", "operation.aspirate"), relationship: "requires" },
    { from: ref("model", "model.exact-serial-dilution"), to: ref("operation", "operation.dispense"), relationship: "requires" },
    { from: ref("model", "model.exact-serial-dilution"), to: ref("operation", "operation.mix"), relationship: "requires" },
    { from: ref("planning", "planning.operational-run"), to: ref("operation", "operation.attach-tips"), relationship: "requires" },
    { from: ref("planning", "planning.operational-run"), to: ref("operation", "operation.aspirate"), relationship: "requires" },
    { from: ref("interaction", "interaction.observation-ingestion"), to: ref("object", "plate.96-well-layout"), relationship: "requires" },
    { from: ref("model", "model.xtt-metabolic-activity"), to: ref("interaction", "interaction.observation-ingestion"), relationship: "requires" },
    { from: ref("model", "model.broth-microdilution-endpoint"), to: ref("model", "model.exact-serial-dilution"), relationship: "requires" },
  ],
  examples: [],
} satisfies CapabilityManifestFragment);
